import Foundation

/// Central data source for all BBC Radio stations
struct RadioStationsData {

    static let allStations: [RadioStation] = [
        // MARK: - National Stations
        RadioStation(name: "Radio 1", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_01505109/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_radio_one"),
        RadioStation(name: "Radio 1Xtra", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_92079267/live/ww/bbc_1xtra/bbc_1xtra.isml/bbc_1xtra-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_1xtra"),
        RadioStation(name: "Radio 1Dance", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_62063831/live/ww/bbc_radio_one_dance/bbc_radio_one_dance.isml/bbc_radio_one_dance-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_radio_one_dance"),
        RadioStation(name: "Radio 1 Anthems", streamURL: URL(string: "https://as-hls-uk-live.akamaized.net/pool_11351741/live/uk/bbc_radio_one_anthems/bbc_radio_one_anthems.isml/bbc_radio_one_anthems-audio%3d96000.norewind.m3u8")!, category: .national, isUKOnly: true, serviceId: "bbc_radio_one_anthems"),
        RadioStation(name: "Radio 2", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_74208725/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_radio_two"),
        RadioStation(name: "Radio 3", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_23461179/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_radio_three"),
        RadioStation(name: "Radio 3 Unwind", streamURL: URL(string: "https://as-hls-uk-live.akamaized.net/pool_30624046/live/uk/bbc_radio_three_unwind/bbc_radio_three_unwind.isml/bbc_radio_three_unwind-audio%3d96000.norewind.m3u8")!, category: .national, isUKOnly: true, serviceId: "bbc_radio_three_unwind"),
        RadioStation(name: "Radio 4", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_55057080/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_radio_fourfm"),
        RadioStation(name: "Radio 4 Extra", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_26173715/live/ww/bbc_radio_four_extra/bbc_radio_four_extra.isml/bbc_radio_four_extra-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_radio_four_extra"),
        RadioStation(name: "Radio 5 live", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_89021708/live/ww/bbc_radio_five_live/bbc_radio_five_live.isml/bbc_radio_five_live-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_radio_five_live"),
        RadioStation(name: "Radio 5 Live sports extra", streamURL: URL(string: "https://as-hls-uk-live.akamaized.net/pool_47700285/live/uk/bbc_radio_five_live_sports_extra/bbc_radio_five_live_sports_extra.isml/bbc_radio_five_live_sports_extra-audio%3d96000.norewind.m3u8")!, category: .national, isUKOnly: true, serviceId: "bbc_radio_five_live_sports_extra"),
        RadioStation(name: "Radio 6 Music", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_81827798/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_6music"),
        RadioStation(name: "Asian Network", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_22108647/live/ww/bbc_asian_network/bbc_asian_network.isml/bbc_asian_network-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_asian_network"),
        RadioStation(name: "World Service", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_87948813/live/ww/bbc_world_service/bbc_world_service.isml/bbc_world_service-audio%3d96000.norewind.m3u8")!, category: .national, serviceId: "bbc_world_service"),

        // MARK: - Nations & Regions (Scotland, Wales, Northern Ireland)
        RadioStation(name: "Radio Scotland FM", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_43322914/live/ww/bbc_radio_scotland_fm/bbc_radio_scotland_fm.isml/bbc_radio_scotland_fm-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_scotland_fm"),
        RadioStation(name: "Radio Scotland MW", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_59378121/live/ww/bbc_radio_scotland_mw/bbc_radio_scotland_mw.isml/bbc_radio_scotland_mw-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_scotland_mw"),
        RadioStation(name: "Radio nan Gaidheal", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_01935182/live/ww/bbc_radio_nan_gaidheal/bbc_radio_nan_gaidheal.isml/bbc_radio_nan_gaidheal-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_nan_gaidheal"),
        RadioStation(name: "Radio Orkney", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_50082558/live/ww/bbc_radio_orkney/bbc_radio_orkney.isml/bbc_radio_orkney-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_orkney"),
        RadioStation(name: "Radio Wales", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_97517794/live/ww/bbc_radio_wales_fm/bbc_radio_wales_fm.isml/bbc_radio_wales_fm-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_wales_fm"),
        RadioStation(name: "Radio Cymru", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_24792333/live/ww/bbc_radio_cymru/bbc_radio_cymru.isml/bbc_radio_cymru-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_cymru"),
        RadioStation(name: "Radio Cymru 2", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_98610936/live/ww/bbc_radio_cymru_2/bbc_radio_cymru_2.isml/bbc_radio_cymru_2-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_cymru_2"),
        RadioStation(name: "Radio Ulster", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_31244774/live/ww/bbc_radio_ulster/bbc_radio_ulster.isml/bbc_radio_ulster-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_ulster"),
        RadioStation(name: "Radio Foyle", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_43178797/live/ww/bbc_radio_foyle/bbc_radio_foyle.isml/bbc_radio_foyle-audio%3d96000.norewind.m3u8")!, category: .nations, serviceId: "bbc_radio_foyle"),

        // MARK: - Regional Stations (England)
        RadioStation(name: "BBC CWR", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_79805333/live/ww/bbc_radio_coventry_warwickshire/bbc_radio_coventry_warwickshire.isml/bbc_radio_coventry_warwickshire-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_coventry_warwickshire"),
        RadioStation(name: "Radio Berkshire", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_64162474/live/ww/bbc_radio_berkshire/bbc_radio_berkshire.isml/bbc_radio_berkshire-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_berkshire"),
        RadioStation(name: "Radio Bristol", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_41858929/live/ww/bbc_radio_bristol/bbc_radio_bristol.isml/bbc_radio_bristol-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_bristol"),
        RadioStation(name: "Radio Cambridge", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_21074581/live/ww/bbc_radio_cambridge/bbc_radio_cambridge.isml/bbc_radio_cambridge-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_cambridge"),
        RadioStation(name: "Radio Cornwall", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_72477894/live/ww/bbc_radio_cornwall/bbc_radio_cornwall.isml/bbc_radio_cornwall-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_cornwall"),
        RadioStation(name: "Radio Cumbria", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_85294020/live/ww/bbc_radio_cumbria/bbc_radio_cumbria.isml/bbc_radio_cumbria-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_cumbria"),
        RadioStation(name: "Radio Derby", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_63732303/live/ww/bbc_radio_derby/bbc_radio_derby.isml/bbc_radio_derby-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_derby"),
        RadioStation(name: "Radio Devon", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_08856933/live/ww/bbc_radio_devon/bbc_radio_devon.isml/bbc_radio_devon-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_devon"),
        RadioStation(name: "Radio Essex", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_23657270/live/ww/bbc_radio_essex/bbc_radio_essex.isml/bbc_radio_essex-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_essex"),
        RadioStation(name: "Radio Gloucestershire", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_74607547/live/ww/bbc_radio_gloucestershire/bbc_radio_gloucestershire.isml/bbc_radio_gloucestershire-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_gloucestershire"),
        RadioStation(name: "Radio Guernsey", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_65313722/live/ww/bbc_radio_guernsey/bbc_radio_guernsey.isml/bbc_radio_guernsey-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_guernsey"),
        RadioStation(name: "Radio Hereford Worcester", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_80112859/live/ww/bbc_radio_hereford_worcester/bbc_radio_hereford_worcester.isml/bbc_radio_hereford_worcester-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_hereford_worcester"),
        RadioStation(name: "Radio Humberside", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_43379345/live/ww/bbc_radio_humberside/bbc_radio_humberside.isml/bbc_radio_humberside-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_humberside"),
        RadioStation(name: "Radio Jersey", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_14000630/live/ww/bbc_radio_jersey/bbc_radio_jersey.isml/bbc_radio_jersey-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_jersey"),
        RadioStation(name: "Radio Kent", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_17754185/live/ww/bbc_radio_kent/bbc_radio_kent.isml/bbc_radio_kent-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_kent"),
        RadioStation(name: "Radio Lancashire", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_98146551/live/ww/bbc_radio_lancashire/bbc_radio_lancashire.isml/bbc_radio_lancashire-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_lancashire"),
        RadioStation(name: "Radio Leeds", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_50115440/live/ww/bbc_radio_leeds/bbc_radio_leeds.isml/bbc_radio_leeds-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_leeds"),
        RadioStation(name: "Radio Leicester", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_04542919/live/ww/bbc_radio_leicester/bbc_radio_leicester.isml/bbc_radio_leicester-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_leicester"),
        RadioStation(name: "Radio Lincolnshire", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_77667780/live/ww/bbc_radio_lincolnshire/bbc_radio_lincolnshire.isml/bbc_radio_lincolnshire-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_lincolnshire"),
        RadioStation(name: "Radio London", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_98137350/live/ww/bbc_london/bbc_london.isml/bbc_london-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_london"),
        RadioStation(name: "Radio Manchester", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_25317916/live/ww/bbc_radio_manchester/bbc_radio_manchester.isml/bbc_radio_manchester-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_manchester"),
        RadioStation(name: "Radio Merseyside", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_46699767/live/ww/bbc_radio_merseyside/bbc_radio_merseyside.isml/bbc_radio_merseyside-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_merseyside"),
        RadioStation(name: "Radio Newcastle", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_46887953/live/ww/bbc_radio_newcastle/bbc_radio_newcastle.isml/bbc_radio_newcastle-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_newcastle"),
        RadioStation(name: "Radio Norfolk", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_61510571/live/ww/bbc_radio_norfolk/bbc_radio_norfolk.isml/bbc_radio_norfolk-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_norfolk"),
        RadioStation(name: "Radio Northampton", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_73827654/live/ww/bbc_radio_northampton/bbc_radio_northampton.isml/bbc_radio_northampton-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_northampton"),
        RadioStation(name: "Radio Nottingham", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_96088503/live/ww/bbc_radio_nottingham/bbc_radio_nottingham.isml/bbc_radio_nottingham-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_nottingham"),
        RadioStation(name: "Radio Oxford", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_19212690/live/ww/bbc_radio_oxford/bbc_radio_oxford.isml/bbc_radio_oxford-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_oxford"),
        RadioStation(name: "Radio Sheffield", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_19967704/live/ww/bbc_radio_sheffield/bbc_radio_sheffield.isml/bbc_radio_sheffield-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_sheffield"),
        RadioStation(name: "Radio Shropshire", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_83478576/live/ww/bbc_radio_shropshire/bbc_radio_shropshire.isml/bbc_radio_shropshire-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_shropshire"),
        RadioStation(name: "Radio Solent", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_11685351/live/ww/bbc_radio_solent/bbc_radio_solent.isml/bbc_radio_solent-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_solent"),
        RadioStation(name: "Radio Solent West Dorset", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_48517520/live/ww/bbc_radio_solent_west_dorset/bbc_radio_solent_west_dorset.isml/bbc_radio_solent_west_dorset-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_solent_west_dorset"),
        RadioStation(name: "Radio Somerset Sound", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_00727706/live/ww/bbc_radio_somerset_sound/bbc_radio_somerset_sound.isml/bbc_radio_somerset_sound-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_somerset_sound"),
        RadioStation(name: "Radio Stoke", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_34849862/live/ww/bbc_radio_stoke/bbc_radio_stoke.isml/bbc_radio_stoke-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_stoke"),
        RadioStation(name: "Radio Suffolk", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_18067288/live/ww/bbc_radio_suffolk/bbc_radio_suffolk.isml/bbc_radio_suffolk-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_suffolk"),
        RadioStation(name: "Radio Surrey", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_27374427/live/ww/bbc_radio_surrey/bbc_radio_surrey.isml/bbc_radio_surrey-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_surrey"),
        RadioStation(name: "Radio Sussex", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_76643803/live/ww/bbc_radio_sussex/bbc_radio_sussex.isml/bbc_radio_sussex-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_sussex"),
        RadioStation(name: "Radio Tees", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_08918172/live/ww/bbc_tees/bbc_tees.isml/bbc_tees-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_tees"),
        RadioStation(name: "Radio Wiltshire", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_44240917/live/ww/bbc_radio_wiltshire/bbc_radio_wiltshire.isml/bbc_radio_wiltshire-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_wiltshire"),
        RadioStation(name: "Radio WM", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_05353924/live/ww/bbc_wm/bbc_wm.isml/bbc_wm-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_wm"),
        RadioStation(name: "Radio York", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_90848428/live/ww/bbc_radio_york/bbc_radio_york.isml/bbc_radio_york-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_radio_york"),
        RadioStation(name: "Three Counties Radio", streamURL: URL(string: "https://as-hls-ww-live.akamaized.net/pool_69997923/live/ww/bbc_three_counties_radio/bbc_three_counties_radio.isml/bbc_three_counties_radio-audio%3d96000.norewind.m3u8")!, category: .regional, serviceId: "bbc_three_counties_radio")
    ]

    /// Returns stations organized by category
    static var stationsByCategory: [RadioStationCategory: [RadioStation]] {
        Dictionary(grouping: allStations, by: { $0.category })
    }

    /// Returns sorted categories
    static var sortedCategories: [RadioStationCategory] {
        RadioStationCategory.allCases.sorted { $0.sortOrder < $1.sortOrder }
    }
}
